### ISSUE TITLE
[timetable-DWH] Ресерч нового источника расписания

### ISSUE THREAD

**Issue by mixx3** [profcomff/dwh-definitions#55]
цифровой университет (вроде так называется) разрабатывает много сервисов для физфака, один из них это расписание 
https://phys.test.my.msu.ru/#/public/schedule
у них есть публичный апи примено вот но такому url https://api.test.my.msu.ru/gateway/public/api/v1/public_content/lessons?schedule_id%5B%5D=1&course_id=2&flow_id=1&date_from=2024-06-02&date_to=2024-06-30
нужно исследовать возможность заливки расписания в наше хранилище
defenition of done:
1)ответить на вопросы: можно ли заливать расписание, как часто можно делать запросы, есть ли какая-то аутентификация
2) написать какой-нибудь скрипт, чтобы удобно было с его помощью отправлять запросы
по вопросам можно идти к 
@mixx3 
@Arzangulyan 
@dyakovri

**Comment by mixx3** [comment]
@Zimovchik, спроси у @Arzangulyan по поводу ручки для групп
нужно узнать как получать список групп

**Comment by mixx3** [comment]
1) сделать схему в definitions 
OdsTimetableApi с полями
id -
group_name - наименование группы (str)
lesson_name - наимернование пары (str)
lesson_from_dttm - дата и время начала пары (str или timestamp)
lesson_to_dttm - дата и время конца пары (str или timestamp)
lecturer_name - full name преподавателя (str)

**Comment by Zimovchik** [comment]
Функция которая забирает данные из api
`import requests
import json
from datetime import datetime, timedelta
import logging
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

def get_group_schedule(group_number: int | str, course_id: int, flow_id: int, date_from: datetime, date_to: datetime):
    url = "https://api.test.my.msu.ru/gateway/public/api/v1/public_content/lessons"
    values_to_keep = ["id", "date", "time_from", "time_to", "schedule_id", "discipline", "classroom", "conducting_way", "lesson_type", "teacher_users", "study_groups"]
    params = {
        "schedule_id[]": "1",
        "course_id": str(course_id),
        "flow_id": str(flow_id),
        "date_from": date_from.strftime("%Y-%m-%d"),
        "date_to": date_to.strftime("%Y-%m-%d")
    }
    try:
        response = requests.get(url, params=params)
        logging.info(f"Successfully fetched schedule for group {group_number} from {date_from} to {date_to}. status: {response.status_code}")
        if response.status_code == 200:
            lessons = response.json()["result"]["data"]
        else:
            return None
    except requests.exceptions.RequestException as e:
        logging.error(f"Error fetching schedule for group {group_number}: {e}")
        return None
    lessons = filter(lambda lesson: (
                    (lesson["study_groups"][0]["type"] == "simple" and lesson["study_groups"][0]["name"] == str(group_number)))
                    or (lesson["study_groups"][0]["type"] == "separation" and lesson["study_groups"][0]["base_groups"][0]["name"] == str(group_number))
                    or ((lesson["study_groups"][0]["type"] == "union" and any(group["name"] == str(group_number) for group in lesson["study_groups"][0]["base_groups"]))),
                    lessons)
    lessons = list(lessons)
    res = []
    for lesson in lessons:
        res.append({key : lesson[key] for key in values_to_keep})
    return res

def insert_schedule_into_db(schedule_data: list[dict]):
    """Загружает данные в stg таблицу RawTimetableApi

    Args:
        :param schedule_data: принимает данные, которые возвращает функция get_group_schedule
    """
    `

**Comment by Zimovchik** [comment]
- Написать функцию insert_schedule_into_db. (Видимо надо сразу делать dag)

**Comment by mixx3** [comment]
да, ручки закрытые
поэтому придется как-то забирать всё нужное из ручки расписания)
